[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.125.7"  # or specify a specific version like "0.117.0"
